x = int(input("enter runs scored by player 1: "))
y = int(input("enter runs scored by player 2: "))
z = int(input("enter runs scored by player 3: "))
print("strike rate of player 1: ", x*(100/60))
print("strike rate of player 2: ", y*(100/60))
print("strike rate of player 3: ", z*(100/60))
print("runs scored by player 1 if played 60 balls more: ", x*2)
print("runs scored by player 2 if played 60 balls more: ", y*2)
print("runs scored by player 3 if played 60 balls more: ", z*2)
print("maximum 6's player 1 can hit: ", x//6)
print("maximum 6's player 2 can hit: ", y//6)
print("maximum 6's player 3 can hit: ", z//6)
