name = input("enter your name:")
branch = input("enter your branch:")
gender = input('enter your gender:')
college = input("enter college name:")
age = int(input("enter your age:"))
print(name)
print(branch)
print(gender)
print(college)
print(age)
